### ISSUE TITLE
个别圆形小图标有偏心问题

### ISSUE THREAD

**Issue by MarsGT** [heyui/heyui-admin#10]
圆形图标里的文字或者 icon 不居中。
看图比较直观：
![截图](https://user-images.githubusercontent.com/13759774/54282571-3de1bc80-45d7-11e9-9f3e-a307b253819b.png)

**Comment by vvpvvp** [comment]
![image](https://user-images.githubusercontent.com/7303371/54285935-dbd88580-45dd-11e9-8348-669034c86c05.png)

能提供一下浏览器以及操作系统信息吗？

**Comment by MarsGT** [comment]
Windows 10 家庭中文版 1809（系统版本17763.379）
浏览器为 Firefox 65.0.2

**Comment by vvpvvp** [comment]
目前，我们在win10下面的firefox系统中暂时没有发现这个问题，如果你找到解决方案的话，请提pr给我们，多谢🙏。
