### ISSUE TITLE
在两个文件里使用了未定义的类型 BMap

### ISSUE THREAD

**Issue by gclove** [heyui/heyui-admin#11]
`BMap`,  `BMAP_NORMAL_MAP`, `BMAP_HYBRID_MAP` 没有定义

> src/components/common/baidu-map/baidu-map.vue

```js
let map = new BMap.Map(this.$el);
```

> src/components/demo-components/components/baidu-map.vue

```js
new BMap.MapTypeControl({
      mapTypes: [BMAP_NORMAL_MAP, BMAP_HYBRID_MAP]
})

var local = new BMap.LocalSearch
```

**Comment by vvpvvp** [comment]
我的基本上提供了一个基础定义，大家可以根据自己的需求进行扩展。

不过，还是欢迎提pr。
