### ISSUE TITLE
按照github首页指示，无法顺利在本地运行项目

### ISSUE THREAD

**Issue by 12212021** [heyui/heyui-admin#12]
依照github首页的说明，采用Vue-cli在本地启动调试，控制台报错
<img width="1022" alt="cca4ef63ea80f9c461dd1692e36ca7b7" src="https://user-images.githubusercontent.com/24203822/54509350-3c701580-4984-11e9-838c-4d138f365cd7.png">

找了下原因，好像是vue.config.js配置文件内devServer对象下面的proxy对象为空对象的原因，全部注释就好了。
![image](https://user-images.githubusercontent.com/24203822/54509432-7f31ed80-4984-11e9-89dd-7e9e75362a8b.png)

其实也不是什么问题。

**Comment by vvpvvp** [comment]
sorry，我把hey-cli的配置放在这里了，我改一下模板。
