### ISSUE TITLE
怎样去掉ajax请求时的/api 前缀

### ISSUE THREAD

**Issue by quqiufeng** [heyui/heyui-admin#27]
` devServer: {
      proxy: {
        '/api/': {
          target: 'http://admin5.test.com/'
        },
        changeOrigin: true,
        pathRewrite: {
          '/api': '/'
        }
      },
      historyApiFallback: true
    },`
   pathRewrite 无效

**Comment by vvpvvp** [comment]
https://github.com/chimurai/http-proxy-middleware#example

**Comment by quqiufeng** [comment]
可以不用这个么
后端是php

**Comment by vvpvvp** [comment]
这个和后端使用什么技术没有关系的。
