### ISSUE TITLE
[feat] Tab栏数量过多时，展示建议

### ISSUE THREAD

**Issue by xkcoding** [heyui/heyui-admin#28]
现在Tab栏页签数量过多的时候，会给每个页签压缩，影响美观，建议增加滚动条或者左右滚动选择页签的功能

**Comment by vvpvvp** [comment]
我是参考的chrome的标签栏交互，总的来说，这种模式还是适用性比较强的。
或者建议限制用户打开的最多tab标签，不然从使用角度来说，滚动还是不是特别好。

**Comment by xkcoding** [comment]
恩，感谢回复，限制数量也是一种方法
还是建议和element-ui那种 
![image](https://user-images.githubusercontent.com/10429917/59573815-4e7a6500-90e7-11e9-84a6-baa85e747c7c.png)
