### ISSUE TITLE
IE 菜单，多选框，单选等无法选中

### ISSUE THREAD

**Issue by iYoochg** [heyui/heyui-admin#29]
自测  IE11 环境下

admin  菜单点击文字部分无法展开子菜单

![image](https://user-images.githubusercontent.com/42759223/59576711-43c5cd00-90f3-11e9-8662-84f87fb389dc.png)

![image](https://user-images.githubusercontent.com/42759223/59576758-62c45f00-90f3-11e9-9a99-283c1f859bf4.png)
![image](https://user-images.githubusercontent.com/42759223/59576798-838cb480-90f3-11e9-9540-cf468300143f.png)

如以上截图   红框内的区域点击无法触发事件    篮框内  红框外的空白区域才能触发事件
（admin项目中，正常heyui项目中没有该问题）

**Comment by vvpvvp** [comment]
没有复现出来，我测试的是线上的版本。

https://admin.heyui.top/

**Comment by iYoochg** [comment]
**文字较长预警（我把情况讲清楚点）**
因为我是mac，所以之前测试时使用的是safari的ie代理，访问admin.heyui.top（与我们自己的项目，使用的也是admin-heyui），如主题所诉，红框内的点击无法触发事件
后面你说没有复现出来，我就在虚拟机的真实windows系统中的ie里测试了下，主题的我所截图的那几个地方都没有问题了，这是比较奇怪的。不过真实ie里可以，那就不用管了

（**重点：category组件复选框还是无法选中**）但是发现category组件的复选框无法选中，这个问题是不管是在我的safari中的ie代理模式，或者是真实windows系统的ie中，都不行。
我试了heyui官网的Category组件使用示例，都真实ie中也是可以的 没有问题
我加入到admin中，却是不行（chrome都可以），
因为admin.heyui.top中没有使用到category组件，所以没办法确定在admin中加category就有问题（这里如果您方便，可以在admin中加个category测试下）
**如果有需要，可以联系我，让你进我们系统看下，重现下**

附加说明：
我自己个人之前也有个项目，也是用admin-heyui，不过导入方式不一样，我是搭建vue-cli，然后把admin-heyui的组件复制过来用的
这个项目在我safari的ie代理模式中不会有主题说的红框中区域点击无效，**没有问题**

我现在工作的项目是用直接clone github上的admin的，会有safari的ie代理模式中不会有主题说的红框中区域点击无效的问题，和category复选框无法选中的问题

category组件对我们项目中比较重要，用在一个关键的地方，需要您的帮助   谢谢

怕说不明白，所以比较啰嗦

**Comment by vvpvvp** [comment]
是这样子的，heyui-admin的heyui版本，我一直都会更新，你能提供一下你 出错 的admin中的heyui版本号吗？这样复现更加准确一些。

然后就是，附加说明有点长，我确定一下。
现在遇到的问题就是 admin项目 在 ie 下使用 Category组件 会存在无法选中的问题。

至于复选框有没有问题，我已经读不懂了.....

**Comment by iYoochg** [comment]
复选框没有问题

heyui版本是1.21.1

**Comment by vvpvvp** [comment]
IE上测试也没有发现问题。
