### ISSUE TITLE
wangeditor存在xss漏洞建议更换

### ISSUE THREAD

**Issue by luterc** [heyui/heyui-admin#44]
* 问题描述：
参见 https://nodesecurity.io/advisories/876
wangeditor可能会被XSS攻击
另外：
wangeditor已经好几年不维护了
* 改进建议
更换富文本编辑器为其他，比如NEditor(UEditor) tinyMCS,CKEditor等

**Comment by vvpvvp** [comment]
多谢你的建议。
实际项目里，我只是做了一个简单的调用。
我后期会参考你的建议修改为其他的编辑器。
