### ISSUE TITLE
希望添加拖拽排序的组件或者功能

### ISSUE THREAD

**Issue by bytehub** [heyui/heyui-admin#46]
希望能有个表格拖拽排序的功能,手动维护表格数据的顺序,虽然可以通过添加序号列排序,但是维护序号列容易重复或者冲突,不是那么方便

**Comment by vvpvvp** [comment]
建议你添加上移，下移按钮处理，这样就不会存在冲突的问题。

**Comment by vvpvvp** [comment]
本身现在的表格功能太过复杂，不建议添加更多功能。
