### ISSUE TITLE
IE 兼容问题

### ISSUE THREAD

**Issue by Iglong** [heyui/heyui-admin#6]
不兼容IE

**Comment by vvpvvp** [comment]
请描述清楚bug，浏览器版本，操作系统。

**Comment by Iglong** [comment]
npm install --save-dev -polyfill
npm install --save-dev babel-polyfill
问题解决不过common 有语法错误提示。

**Comment by Iglong** [comment]
windows 7,10。 IE:8~11.5

**Comment by vvpvvp** [comment]
不好意思，我一直以为我加了babel-polyfill，补充了一下，不过ie上面还是只支持到Ie9+.
