### ISSUE TITLE
建议路由和菜单配置文件合并

### ISSUE THREAD

**Issue by ChartWay** [heyui/heyui-admin#60]
目前两个文件分开，感觉比较多余，很多重复配置工作，而且对原来使用iview或者element的用户不友好。
建议对文件进行合并，增加一个是否菜单的参数来识别。

**Comment by vvpvvp** [comment]
路由和菜单本身大部分信息是一致的，但是一个属于系统设计，一个是业务设计，后期在所难免会有差异，不过，如果你的业务重合度很高，我觉得你可以自己改一下就可以了。
