### ISSUE TITLE
疑问：Table组件丢失expandAll方法

### ISSUE THREAD

**Issue by windinternet** [heyui/heyui-admin#83]
我刚开始初学，使用heyui-admin在尝试做一些管理系统，当我有树型表格的需求时（例如权限菜单），通过查看官方文档，实现了这个效果，其中的交互逻辑使用到了expandAll方法，目的是加载完成后自动展开，没有任何问题，我重新建立了一个项目，将相同的代码复制过去时，也能得到较好的树型表格，当代码执行到expandAll，却抛出了expandAll不是一个方法的错误，我在两个项目调用该方法的前面打印了当前table的实例，比较之后发现，我新建的项目的确丢失了展开和收起方法，其他一致，package.json里面引用版本也是一致的。大佬能否帮忙分析一下是哪里的问题呢，非常感谢！

**Comment by windinternet** [comment]
尝试过删除node_module重新安装依赖包，以及更新依赖包，刚开始的第一个能正常使用的项目用的是：
   "hey-global": "0.0.1",
    "hey-log": "0.0.8",
    "hey-utils": "^1.0.2",
    "heyui": "^1.25.1",
默认版本，更新后：
    "hey-global": "0.0.1",
    "hey-log": "0.0.8",
    "hey-utils": "^1.0.2",
    "heyui": "^1.28.0"
依旧丢失expandAll方法
还尝试过：cnpm 与 npm 都没有得到解决

**Comment by vvpvvp** [comment]
打开Tree结构的table所有的节点是1.26.0+新增的，你可以看下你node_module安装的版本是否正常。
