### ISSUE TITLE
关于顶部标签页的右键更多功能

### ISSUE THREAD

**Issue by Fun005** [heyui/heyui-admin#9]
如题，有没有考虑更加右键更多功能？比如关闭当前标签页、关闭其他、关闭所有，等等

**Comment by Fun005** [comment]
很喜欢heyui以及hey-admin的风格，希望以后能为heyui献上自己的一份力量。heyui加油

**Comment by vvpvvp** [comment]
有考虑，目前正在写文档，这个在后续补充添加。

**Comment by bhuh12** [comment]
> 有考虑，目前正在写文档，这个在后续补充添加。

我新开源的基于 ` Vue Router` 的多页签组件，欢迎试用呢：
[https://github.com/bhuh12/vue-router-tab](https://github.com/bhuh12/vue-router-tab)

## 功能

- [x] 响应路由变化来打开或切换页签
- [x] 页签关闭和刷新，右键菜单操作
- [x] 全局和针对特定路由的页签规则配置
- [x] 初始页签数据，进入页面时默认显示的页签
- [x] 内置页签和页面过渡效果，支持自定义配置
- [x] 自定义页签模板
- [x] 动态更新页签信息(标题/图标/提示)
- [x] 页签页面离开 (页签关闭/刷新/替换) 前确认
- [x] 语言配置：zh-CN (默认) / en，自定义语言


**文档：**
[https://bhuh12.github.io/vue-router-tab/](https://bhuh12.github.io/vue-router-tab/)

**演示：**
[https://bhuh12.github.io/vue-router-tab/demo/](https://bhuh12.github.io/vue-router-tab/demo/)

**Comment by qmdx** [comment]
> > 有考虑，目前正在写文档，这个在后续补充添加。
> 
> 我新开源的基于 ` Vue Router` 的多页签组件，欢迎试用呢：
> https://github.com/bhuh12/vue-router-tab
> 
> ## 功能
> * [x]  响应路由变化来打开或切换页签
> * [x]  页签关闭和刷新，右键菜单操作
> * [x]  全局和针对特定路由的页签规则配置
> * [x]  初始页签数据，进入页面时默认显示的页签
> * [x]  内置页签和页面过渡效果，支持自定义配置
> * [x]  自定义页签模板
> * [x]  动态更新页签信息(标题/图标/提示)
> * [x]  页签页面离开 (页签关闭/刷新/替换) 前确认
> * [x]  语言配置：zh-CN (默认) / en，自定义语言
> 
> **文档：**
> https://bhuh12.github.io/vue-router-tab/
> 
> **演示：**
> https://bhuh12.github.io/vue-router-tab/demo/

非常好，建议搞一个 admin ui 使用它
